{{ $namespace := .Values.namespace}}
{{- range .Values.exporters }}
---
# Deployment for promprox
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-exporter
  namespace: {{ $namespace }}
  labels:
    app: {{ .name }}-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}-exporter
  template:
    metadata:
      labels:
        app: {{ .name }}-exporter
    spec:
      containers:
      - name: {{ .name }}-exporter
        image: svenmollinga/promprox:latest
        ports:
        - containerPort: 9090
        env:
        - name: METRIC_URL
          value: "{{ .metricurl }}"
{{- end }}
