# Deployment for promprox
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.exporter.name }}-exporter
  labels:
    app: {{ .Values.exporter.name }}-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.exporter.name }}-exporter
  template:
    metadata:
      labels:
        app: {{ .Values.exporter.name }}-exporter
    spec:
      containers:
      - name: {{ .Values.exporter.name }}-exporter
        image: svenmollinga/promprox:latest
        ports:
        - containerPort: 9090
        env:
        - name: METRIC_URL
          value: "{{ .Values.exporter.metricurl }}"