{{ $namespace := .Values.namespace}}
{{- range .Values.exporters }}
---
# Service for promprox
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-exporter
  namespace: {{ $namespace }}
  labels:
    app: {{ .name }}-exporter
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: {{ .name }}-exporter
{{- end }}
