{{ $namespace := .Values.namespace}}
{{ $prometheus := .Values.prometheus}}
{{- range .Values.exporters }}
---
# Servicemonitor for promprox
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .name }}-exporter
  namespace: {{ $namespace }}
  labels:
    app: {{ .name }}-exporter
    prometheus: {{ $prometheus }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}-exporter
  namespaceSelector:
    any: true
  endpoints:
  - port: metrics
    interval: 1m
{{- end }}
